import { mkdirSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Exports the compiled VeilSwapPair ABI and the root deployments.json into the
 * frontend (`app/src/config/`), keeping the app in lockstep with the contracts.
 * Run after `hardhat compile` and after every deployment.
 */
const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const artifact = JSON.parse(
  readFileSync(join(root, "artifacts", "contracts", "VeilSwapPair.sol", "VeilSwapPair.json"), "utf8")
);

mkdirSync(join(root, "app", "src", "config"), { recursive: true });

const banner = "// AUTO-GENERATED by scripts/export-abi-to-app.ts — do not edit by hand.\n";
writeFileSync(
  join(root, "app", "src", "config", "veilswap-pair-abi.ts"),
  `${banner}export const veilSwapPairAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`
);
copyFileSync(join(root, "deployments.json"), join(root, "app", "src", "config", "deployments.json"));
console.log("Exported VeilSwapPair ABI + deployments.json to app/src/config/");
